#!/usr/bin/env python3
"""Generate release/pyre-windows-constraints.txt from package-versions.yaml.

The output lists monorepo packages as local ``file://`` URLs for PyInstaller
builds. Third-party dependencies are installed separately in build-freeze.ps1.
"""

from __future__ import annotations

import sys
from pathlib import Path
from urllib.parse import urljoin
from urllib.request import pathname2url

try:
    import yaml  # type: ignore[import-untyped]
except ImportError:
    print("Install PyYAML: pip install pyyaml", file=sys.stderr)
    sys.exit(1)

# Install order matches nornir-docker/install-monorepo-editables.sh plus pyre.
PYRE_BOM_ORDER = (
    "nornir_shared",
    "nornir_pools",
    "nornir_imageregistration",
    "nornir_buildmanager",
    "pyre",
)


def _file_url(path: Path) -> str:
    resolved = path.resolve()
    return urljoin("file:", pathname2url(str(resolved)))


def main() -> int:
    release_dir = Path(__file__).resolve().parent
    repo_root = release_dir.parent
    bom_path = release_dir / "package-versions.yaml"
    out_path = release_dir / "pyre-windows-constraints.txt"

    data = yaml.safe_load(bom_path.read_text(encoding="utf-8"))
    packages = data.get("packages") or {}

    lines: list[str] = [
        "# Generated by release/generate_pyre_windows_constraints.py",
        "# Local monorepo packages for Pyre Windows freeze (CPU-only imageregistration).",
        "",
    ]

    for dist in PYRE_BOM_ORDER:
        meta = packages.get(dist)
        if not isinstance(meta, dict):
            print(f"generate_pyre_windows_constraints: missing BOM entry for {dist}", file=sys.stderr)
            return 1
        rel_path = meta.get("path")
        if not rel_path:
            print(f"generate_pyre_windows_constraints: {dist} missing path", file=sys.stderr)
            return 1
        pkg_dir = repo_root / str(rel_path)
        if not pkg_dir.is_dir():
            print(f"generate_pyre_windows_constraints: missing directory {pkg_dir}", file=sys.stderr)
            return 1
        lines.append(f"{dist} @ {_file_url(pkg_dir)}")

    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
