#!/usr/bin/env python3
"""Sync Pyre end-user changelog into release notes and Sphinx docs.

Reads ``nornir-pyre/CHANGELOG.user.md`` (curated, user-facing).

Examples::

    # Print notes for the version in nornir-pyre/pyproject.toml
    python release/sync_pyre_user_changelog.py --notes-only

    # Write GitHub release body + regenerate docs/packages/pyre_changelog.rst
    python release/sync_pyre_user_changelog.py --write-docs --notes-file release/_pyre_release_notes.md
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

_ROOT = Path(__file__).resolve().parents[1]
_CHANGELOG = _ROOT / "nornir-pyre" / "CHANGELOG.user.md"
_PYPROJECT = _ROOT / "nornir-pyre" / "pyproject.toml"
_DOCS_RST = _ROOT / "docs" / "packages" / "pyre_changelog.rst"

_VERSION_HEADING = re.compile(r"^##\s+(\d+\.\d+\.\d+)\s*$", re.MULTILINE)
_PYPROJECT_VERSION = re.compile(
    r'(?m)^version\s*=\s*["\'](\d+\.\d+\.\d+)["\']\s*$'
)


def read_pyre_version(pyproject: Path = _PYPROJECT) -> str:
    text = pyproject.read_text(encoding="utf-8")
    match = _PYPROJECT_VERSION.search(text)
    if match is None:
        raise SystemExit(f"Could not find [project] version in {pyproject}")
    return match.group(1)


def parse_changelog(text: str) -> dict[str, str]:
    """Map version string -> section body (markdown, without the ## heading)."""
    matches = list(_VERSION_HEADING.finditer(text))
    sections: dict[str, str] = {}
    for index, match in enumerate(matches):
        version = match.group(1)
        start = match.end()
        end = matches[index + 1].start() if index + 1 < len(matches) else len(text)
        body = text[start:end].strip()
        sections[version] = body
    return sections


def section_for_version(changelog_path: Path, version: str) -> str:
    text = changelog_path.read_text(encoding="utf-8")
    sections = parse_changelog(text)
    if version not in sections:
        raise SystemExit(
            f"No '## {version}' section in {changelog_path}. "
            "Add a curated user-facing section before publishing."
        )
    return sections[version]


def release_notes_markdown(version: str, section_body: str) -> str:
    return (
        f"# Pyre {version} (Windows installer)\n\n"
        f"{section_body}\n\n"
        "---\n\n"
        f"- Versioned installer: `Pyre-{version}-Setup.exe`\n"
        "- Always-latest download (docs link here): `Pyre-Setup.exe`\n"
        "- Older builds remain on prior `pyre-*` releases on this repository.\n"
        "- Install guide: https://nornir.github.io/packages/pyre_install.html\n"
    )


def _md_bullet_to_rst(line: str) -> str:
    stripped = line.strip()
    if stripped.startswith("- "):
        return f"* {stripped[2:]}"
    return stripped


def changelog_to_rst(changelog_path: Path) -> str:
    """Convert the user changelog markdown into an RST page body."""
    text = changelog_path.read_text(encoding="utf-8")
    sections = parse_changelog(text)
    lines = [
        "Pyre user changelog",
        "===================",
        "",
        "End-user notes for the Windows installer. Maintainer source:",
        "``nornir-pyre/CHANGELOG.user.md`` (regenerated by",
        "``release/sync_pyre_user_changelog.py``).",
        "",
        "Download the latest installer: |pyre-windows-installer-latest|",
        "(currently |pyre-windows-installer-version|).",
        "",
        "Older installers remain on the repository",
        "`Releases page <https://github.com/jamesra/nornir/releases>`_",
        "(look for tags ``pyre-*``).",
        "",
    ]
    for version in sorted(sections.keys(), key=lambda v: tuple(int(p) for p in v.split(".")), reverse=True):
        lines.append(version)
        lines.append("-" * len(version))
        lines.append("")
        for raw in sections[version].splitlines():
            if not raw.strip():
                lines.append("")
                continue
            lines.append(_md_bullet_to_rst(raw))
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--version",
        help="Pyre version (default: nornir-pyre/pyproject.toml)",
    )
    parser.add_argument(
        "--changelog",
        type=Path,
        default=_CHANGELOG,
        help="Path to CHANGELOG.user.md",
    )
    parser.add_argument(
        "--notes-file",
        type=Path,
        help="Write GitHub release notes markdown to this path",
    )
    parser.add_argument(
        "--notes-only",
        action="store_true",
        help="Print release notes for --version to stdout",
    )
    parser.add_argument(
        "--write-docs",
        action="store_true",
        help=f"Regenerate {_DOCS_RST.relative_to(_ROOT).as_posix()}",
    )
    args = parser.parse_args(argv)

    version = args.version or read_pyre_version()
    body = section_for_version(args.changelog, version)
    notes = release_notes_markdown(version, body)

    if args.notes_only:
        sys.stdout.write(notes)
        return 0

    if args.notes_file is not None:
        args.notes_file.parent.mkdir(parents=True, exist_ok=True)
        args.notes_file.write_text(notes, encoding="utf-8")
        print(f"Wrote {args.notes_file}")

    if args.write_docs:
        _DOCS_RST.parent.mkdir(parents=True, exist_ok=True)
        _DOCS_RST.write_text(changelog_to_rst(args.changelog), encoding="utf-8")
        print(f"Wrote {_DOCS_RST}")

    if args.notes_file is None and not args.write_docs:
        parser.error("Specify --notes-file and/or --write-docs (or --notes-only)")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
